[master] Add script processor
craftercms/docs pull request #1123
Opened 2020-12-30 16:34 UTC by alhambrav

### Ticket reference or full description of what's in the PR
Add script processor

2021-01-04 20:30 UTC, sumerjabri requested changes

2021-01-04 20:30 UTC, sumerjabri commented on source/system-administrators/deployer/processors-guide.rst
> +Script Processor
Groovy Script Processor

2021-01-04 20:30 UTC, sumerjabri commented on source/system-administrators/deployer/processors-guide.rst
> +Processor that executes scripts in a sandbox
A site-specific custom Groovy processor that can process published content.

2021-01-04 20:30 UTC, sumerjabri commented on source/system-administrators/deployer/processors-guide.rst
> +    :caption: *Script Processor*
Groovy Script Processor

2021-01-05 16:31 UTC, sumerjabri requested changes
Please reference: https://javadoc.craftercms.org/3.1.11/deployer/org/craftercms/deployer/impl/processors/AbstractMainDeploymentProcessor.html

To show how to implement the Processor.

2021-01-05 19:14 UTC, jdrossl requested changes

2021-01-05 19:14 UTC, jdrossl commented on source/system-administrators/deployer/processors-guide.rst
> +A site-specific custom Groovy processor that can process published content.
I'm not sure `site-specific` is accurate here, both the processor and the scripts can be shared

2021-01-05 19:14 UTC, jdrossl commented on source/system-administrators/deployer/processors-guide.rst
> +
For better guidance to developers I think we should include a small example of a valid Groovy script and a short description of the variables available to use

2021-01-06 21:51 UTC, jdrossl approved these changes

2021-01-07 15:54 UTC, sumerjabri approved these changes

2021-01-07 15:54 UTC, merged