[3.1] Add instructions on how to recreate remotes
craftercms/docs pull request #1180
Opened 2021-03-18 17:48 UTC by alhambrav

### Ticket reference or full description of what's in the PR
Add instructions on how to recreate remotes

2021-03-18 19:52 UTC, sumerjabri requested changes

2021-03-18 19:52 UTC, sumerjabri commented on source/system-administrators/activities/clustering.rst
> +.. index:: Studio Clustering, Clustering, Studio's Embedded Database Multi-master Cluster
Please remove the term "multi-master" from all docs.

2021-03-19 14:56 UTC, sumerjabri requested changes

2021-03-19 14:56 UTC, sumerjabri commented on source/system-administrators/activities/clustering/studio-clustering-two-nodes-with-arbiter.rst
> +.. index:: Setup a Two Node Cluster with Studio and a Studio Arbiter, Clustering with Studio Example, Studio's Embedded Database Cluster Example
Remove the words Embedded Database, it's just a Studio Cluster. Please do that throughout or ping me if you see a problem.

2021-03-19 14:56 UTC, sumerjabri commented on source/system-administrators/activities/kubernetes/studio-clustering-with-kubernetes-deployment.rst
> +Shutting down the nodes one by one allows for a graceful shutdown of the embedded database cluster.  The ``cascade`` flag allows killing the pods (shutting down the nodes) one by one.  Remember to se
shutdown of the cluster.

2021-03-22 14:05 UTC, avasquez614 requested changes

2021-03-22 14:05 UTC, avasquez614 commented on source/system-administrators/activities/clustering/changing-git-url-format-in-cluster.rst
> +      java.lang.ClassCastException: org.eclipse.jgit.transport.TransportHttp cannot be cast to org.eclipse.jgit.transport.SshTransport
This error only occurs when you change the URL from SSH to HTTPS. Maybe we need to clarify that?

2021-03-24 18:29 UTC, sumerjabri approved these changes

2021-03-24 18:29 UTC, merged