Update doc for engine headers authentication
craftercms/docs pull request #1189
Opened 2021-03-25 21:55 UTC by jdrossl

https://github.com/craftercms/craftercms/issues/4603

2021-03-26 13:27 UTC, sumerjabri commented on source/site-administrators/engine/engine-headers-based-authentication.rst
> +simple role names to use in the page or url restrictions.  Optional attribute mappings are also available which
URL

2021-03-26 13:28 UTC, sumerjabri commented on source/site-administrators/engine/engine-headers-based-authentication.rst
> +allows exposing attributes from the external authentication.
allow (not allows)

the external authentication authority.

2021-03-26 13:29 UTC, sumerjabri commented on source/site-administrators/engine/engine-headers-based-authentication.rst
> +- MELLON_secure_key (required)
We should reconsider this default prefix in code and here. Once we decide on the code, we can adjust this.

2021-03-26 13:29 UTC, sumerjabri commented on source/site-administrators/engine/engine-headers-based-authentication.rst
> +Add the following, where we are enabling Engine headers authentication and requiring authentication for all urls in the
URLs

2021-03-26 13:32 UTC, sumerjabri requested changes
See notes. Also, hold on merge until we decide the default prefix.

2021-03-26 20:49 UTC, sumerjabri requested changes
Please address the notes.

2021-03-29 15:10 UTC, alhambrav approved these changes

2021-03-29 15:17 UTC, sumerjabri approved these changes

2021-03-29 15:17 UTC, merged