Add user interface config and sidebar excludes/icon colors
craftercms/docs pull request #1347
Opened 2021-09-24 11:56 UTC by alhambrav

### Ticket reference or full description of what's in the PR
Add user interface config and sidebar excludes/icon colors
https://github.com/craftercms/craftercms/issues/4353
https://github.com/craftercms/craftercms/issues/4351

2021-09-27 21:02 UTC, sumerjabri requested changes

2021-09-27 21:02 UTC, sumerjabri commented on source/site-administrators/studio/user-interface-configuration.rst
> +The user interface configuration file defines the widgets shown in the user interface.  It allows the user to configure
Maybe add that the UI is made up of configurable widgets and can be extended or modified by adding/removing/configuring widgets. Plugins can make use of this by adding themselves to the UI where required.

2021-09-29 11:56 UTC, alhambrav commented on source/site-administrators/studio/user-interface-configuration.rst
> +   <siteUi>
All the Studio site configuration files lists the sample config file.  Moved the sample code to a separate file that is linked in the ui config doc that can be expanded/collapsed.  More explanation for the structure will be added in as widgets are documented, with a brief description of widgets in the config and the sidebar excludes and icon color as a start.

2021-09-29 15:25 UTC, sumerjabri approved these changes

2021-09-29 15:25 UTC, merged