Add notes for clustering
craftercms/docs pull request #1544
Opened 2022-09-09 12:06 UTC by alhambrav

### Ticket reference or full description of what's in the PR
- Add note for multi-region considerations

2022-09-16 15:45 UTC, sumerjabri approved these changes

2022-09-21 17:41 UTC, sumerjabri requested changes

2022-09-21 17:41 UTC, sumerjabri commented on source/system-administrators/activities/clustering/cluster-troubleshooting.rst
>  An email will also be sent to configured recipients to inform them of the failure.
... to the configured list of recipients ...

2022-10-20 15:32 UTC, jmendeza commented on source/new-ia/by-role/system-admin/clustering/cluster-troubleshooting.rst
> +required and may be done by following the instructions `here <https://mariadb.com/kb/en/set-global-sql_slave_skip_counter/>`__
If there is a startup failure, Studio will stop and MariaDB will be down. Can we add here instructions to start it up in order to perform the manual fix?

2022-10-20 15:53 UTC, jmendeza requested changes
Please review my comment

2022-10-20 20:57 UTC, jmendeza approved these changes

2022-10-20 21:20 UTC, sumerjabri requested changes

2022-10-20 21:20 UTC, sumerjabri commented on source/new-ia/by-role/system-admin/clustering/cluster-troubleshooting.rst
> +   :caption: *Sample log for a cluster Git sync startup failure*
... an authoring cluster ...

2022-10-20 21:20 UTC, sumerjabri commented on source/system-administrators/activities/clustering/cluster-troubleshooting.rst
> +:is-up-to-date: True
Same for this file.

2022-10-21 19:28 UTC, sumerjabri approved these changes

2022-10-21 19:28 UTC, merged