Update blob stores configuration
craftercms/docs pull request #1571
Opened 2022-11-15 11:36 UTC by alhambrav

### Ticket reference or full description of what's in the PR
Update blob stores configuration on use of AWS profiles instead of credentials in the config

2022-11-15 21:32 UTC, sumerjabri commented
Please update to Blob Store not Blob Stores

2022-11-16 14:49 UTC, avasquez614 requested changes

2023-01-02 18:21 UTC, sumerjabri commented
@avasquez614 is this ready now?

2023-01-16 14:56 UTC, avasquez614 approved these changes

2023-01-16 15:11 UTC, merged