[master] Upgrade MongoDB
craftercms/docs pull request #1764
Opened 2024-01-04 15:30 UTC by alhambrav

### Ticket reference or full description of what's in the PR
Add upgrading MongoDB https://github.com/craftercms/craftercms/issues/6308

2024-01-05 10:32 UTC, phuongnq approved these changes

2024-01-08 16:27 UTC, sumerjabri requested changes
Let's combine into the main file with the necessary caveats that this is for Profile/Social only.

2024-01-08 22:55 UTC, sumerjabri requested changes

2024-01-08 22:55 UTC, sumerjabri commented on source/by-role/system-admin/upgrade/index.rst
> +Crafter Profile and Social version 4.1.3 and later uses MongoDB v6 in the install.
Is this really 4.1.3 or is it in 4.1.2 as well?

2024-01-09 16:04 UTC, sumerjabri approved these changes

2024-01-09 16:04 UTC, merged