Add release notes for 4.1.4
craftercms/docs pull request #1803
Opened 2024-03-15 14:26 UTC by alhambrav

### Ticket reference or full description of what's in the PR
- Add release notes for 4.1.4
- Update docs OAS files with updated OAS files from [Studio](https://github.com/craftercms/studio/pull/3500), [Engine](https://github.com/craftercms/engine/pull/718), [Deployer](https://github.com/craftercms/deployer/pull/438)

2024-03-15 18:39 UTC, sumerjabri commented on source/release-notes/4-1-4.rst
> +Bug Fixes
Let's also include this https://github.com/craftersoftware/craftercms/issues/829

2024-03-20 13:20 UTC, sumerjabri approved these changes

2024-04-03 13:47 UTC, sumerjabri requested changes

2024-04-03 13:47 UTC, sumerjabri commented on source/release-notes/4-1-4.rst
> +Bug Fixes
I still don't see this.

2024-04-15 14:46 UTC, sumerjabri approved these changes

2024-04-25 10:30 UTC, alhambrav commented
Updated release notes to add note for project policy https://github.com/craftercms/craftercms/issues/6104

2024-04-25 17:47 UTC, sumerjabri approved these changes

2024-04-29 19:35 UTC, sumerjabri requested changes

2024-04-29 20:13 UTC, alhambrav commented
Updated release notes (commit https://github.com/craftercms/docs/pull/1803/commits/2c43b74071a0d4fc37b811eb40430d976836e95c and https://github.com/craftercms/docs/pull/1803/commits/e577213de6d080deb4d60df76544ef3f702b11bb) for changing the maximum size of a project/site configuration file https://github.com/craftercms/craftercms/issues/6710

2024-05-01 15:43 UTC, merged