Add release notes for 4.2.0
craftercms/docs pull request #1827
Opened 2024-05-14 14:50 UTC by alhambrav

### Ticket reference or full description of what's in the PR
Add release notes for 4.2.0

Add updated dependencies in release: https://github.com/craftercms/craftercms/issues/5977

2024-05-14 16:40 UTC, sumerjabri requested changes

2024-05-14 16:40 UTC, sumerjabri commented on source/release-notes/4-2-0.rst
> +  - Tuckey to version 5.1.3
Is this the right dependency name? I thought it was `UrlRewriteFilter` or similar.

2024-05-14 16:40 UTC, sumerjabri commented on source/release-notes/4-2-0.rst
> +  - Esapi to version 2.5.3.1
Is this one in all caps? `ESAPI`?

2024-05-14 16:40 UTC, sumerjabri commented on source/release-notes/4-2-0.rst
> +  - Tomcat to version ``10.1.20``
I think we don't list the patch version. Perhaps Tomcat 10 is enough.

2024-05-14 16:40 UTC, sumerjabri commented on source/release-notes/4-2-x-breaking-changes.rst
> +  - CrafterCMS 4.2.x requires Git. |br| See :ref:`Requirements <requirements_supported_platforms>` for more
Is this different from 4.1? If not, can we say something like CrafterCMS 4.1.x onward ...

2024-05-14 16:40 UTC, sumerjabri commented on source/release-notes/4-2-x-breaking-changes.rst
> +  - Studio and Engine SAML configuration now uses a key and certificate for configuration instead of using keystore. |br|
For many of these changes, are they the same as 4.1? Let's discuss if they are.

2024-05-14 17:12 UTC, sumerjabri approved these changes

2024-07-23 14:57 UTC, alhambrav commented
- Commit https://github.com/craftercms/docs/pull/1827/commits/1109441d1c06198fc9837b1723d359487f3d4a7c: Update for Crafter CLI new commands https://github.com/craftercms/craftercms/issues/6941
- Commits https://github.com/craftercms/docs/pull/1827/commits/06c859638e6959502879009ce81cd6bde6200521 and https://github.com/craftercms/docs/pull/1827/commits/0ef02d7bb125097458f8ee8b8b12047cdbcfced0: Update permissions https://github.com/craftersoftware/craftercms/issues/847

2024-07-24 14:37 UTC, alhambrav commented
Commit https://github.com/craftercms/docs/pull/1827/commits/b2c06f3a83887a0f4123d9ebd2268a9fe8af5b61: Update for RTE config for template plugin https://github.com/craftersoftware/craftercms/issues/886

2024-07-24 14:50 UTC, sumerjabri requested changes

2024-07-24 14:50 UTC, sumerjabri commented on source/release-notes/4-2-0.rst
> +  - MariaDb4J to version ``3.1.0.2`` and MariaDB to ``11.3.2``
Keep to `major`.`minor` for MariaDB/4j

2024-07-24 14:50 UTC, sumerjabri commented on source/release-notes/4-2-0.rst
> +  - UrlRewriteFilter to version 5.1.3
Remove patch version.

2024-07-24 14:50 UTC, sumerjabri commented on source/release-notes/4-2-0.rst
> +  - FileUpload to version 2.0.0-M2
Remove patch version.

2024-08-16 14:07 UTC, alhambrav commented
- commit https://github.com/craftercms/docs/pull/1827/commits/231720af8072eb3e2ea9a8821fcd6b94ac0ed5f5: add new options for CLI https://github.com/craftercms/craftercms/issues/7153

2024-08-16 18:23 UTC, russdanner approved these changes

2024-09-20 07:29 UTC, sumerjabri requested changes

2024-09-20 07:29 UTC, sumerjabri commented on source/by-role/author/index.rst
> +.. _author-rte-code-samples:
I think this should be in a different PR since it's not related to the release notes.

2024-09-20 07:29 UTC, sumerjabri commented on source/by-role/system-admin/upgrade/upgrading-server.rst
> +   Remember to read all other release notes in between the version you currently have and the version you are upgrading to as it contains information on the changes that have occurred and steps you m
Same thing?

2024-09-20 07:29 UTC, sumerjabri commented on source/release-notes/4-2-0.rst
> +* `Fixed issue uppercase role names not being recognized by the permission evaluation system <https://github.com/craftercms/craftercms/issues/7001>`__
Mixed case.

2024-09-20 07:29 UTC, sumerjabri commented on source/release-notes/4-2-0.rst
> +* `Fixed issue with \"File Upload From Desktop\" datasource throwing an error when the dialog is open and closed <https://github.com/craftercms/craftercms/issues/6697>`__
opened not open

2024-09-20 07:29 UTC, sumerjabri commented on source/release-notes/4-2-0.rst
>    - MariaDb4J to version ``3.1`` and MariaDB to ``11.3``
Separate into two different lines (to highlight the MariaDB upgrade) and lead with MariaDB not MariaDB4j.

2024-09-20 07:29 UTC, sumerjabri commented on source/release-notes/index.rst
> +   .. note:: CrafterCMS 4.2.x requires Java 21
remove the `.x`

2024-09-24 14:57 UTC, sumerjabri requested changes

2024-09-24 14:57 UTC, sumerjabri commented on source/release-notes/4-2-x-breaking-changes.rst
> +- **Upgrading 3.1.x sites** |br|
Let's make this a section instead of just bolding it.

2024-09-24 18:08 UTC, sumerjabri approved these changes

2024-10-01 13:25 UTC, sumerjabri commented
@rart please look at the UI release notes.

2024-10-10 20:42 UTC, sumerjabri approved these changes

2024-10-11 17:39 UTC, sumerjabri approved these changes

2024-10-16 19:30 UTC, sumerjabri approved these changes

2024-11-07 15:16 UTC, sumerjabri approved these changes

2024-11-14 15:45 UTC, sumerjabri approved these changes

2024-11-14 15:45 UTC, merged