Add document indexing section in deployer #7192
craftercms/docs pull request #1866
Opened 2024-08-27 14:47 UTC by alhambrav

### Ticket reference or full description of what's in the PR
Add document indexing section in deployer https://github.com/craftercms/craftercms/issues/7192

2024-08-27 17:50 UTC, sumerjabri requested changes

2024-08-27 17:50 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +            - application/vnd.openxmlformats-officedocument.presentationml.presentation
How do you add to this list?

2024-08-27 17:50 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +^^^^^^^^^^^^^^^^^
Throughout this PR, change mime to MIME. This also means it's MIME-type or MIME-types.

2024-08-27 17:50 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +Crafter Deployer indexes documents via the following configured items:
While the Deployer performs content indexing, we probably need to reference this higher up in the IA and make it clear(er). Let's discuss where else to point to this or include it. This is core to the system.

2024-08-27 17:50 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +Crafter Deployer indexes documents via the following configured items:
CrafterCMS indexes content items as follows

2024-08-27 17:50 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +
Additionally, CrafterCMS indexes non-text-based content as follows:
[add notes on how we index filenames and meta-data where possible]

2024-08-27 17:50 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +- A full text index of any document that has a mimetype that matches the configured list of mimetypes.
- Full-text indexing of text-based documents like PDFs, MS Office, etc. See the list of supported MIME-types below.

2024-08-27 17:50 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +Mimetypes
Full-text Search MIME-Types

2024-08-27 17:50 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +- Indexing of any remote document that matches the configured list of remote documents pattern
- Full-text indexing of remote documents referenced by local content items, where the local item references match a document pattern [add a reference/link].

2024-08-27 17:50 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +- Indexing of jacketed documents with anything that matches the configured pattern.
- Full-text indexing of text-based documents with a CrafterCMS content wrapper [reference what that is with a link and another link to the jacket example below].

2024-08-27 17:50 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +
- Indexing of filenames and meta-data for other content items. [Check what we do with binary files like .jpg, or similar where we have meta-data but not textual content and explain it here.]

2024-08-27 17:50 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +Note that indexing of documents in authoring and indexing of documents in delivery each have their own configuration.
Use a _note_ directive.

2024-08-27 17:50 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +Note that indexing of documents in authoring and indexing of documents in delivery each have their own configuration.
Indexing is done differently in the authoring environment vs the delivery environment.

Authoring indexing is done to help content authors do their work and is controlled by CrafterCMS. The authoring search index is tuned to help authors and is not used by the project/site for delivery concerns.

On the other hand, delivery indexing is done to enable search and search-based features for the delivery project/site. This is configurable per project/site, and the index is tuned to help end-users use the project/site.

2024-08-27 17:50 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +The list of supported mimetypes determines what's considered a document that should be full-text indexed.
The following is the default list of MIME-types with full-text-search indexing enabled.

2024-08-27 17:50 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +The ``remoteBinaryPathPatterns`` in the config determines what a remote document is via path pattern.
What config? Name it up here before the example.

2024-08-27 17:50 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +The ``metadataPathPatterns`` in the configuration determines if a document should be indexed with the metadata of the
define "configuration" filename (like above)

2024-08-27 17:50 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +The default behavior when a document cannot be indexed is that the Deployer logs the error and moves on. Process commits
This repeats the bullets above. We should pick one.

2024-08-27 17:50 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +commits regardless of success or failure. Some deployments set this to false and force the processor chain to be
This repeats the paragraphs above.

These paragraphs regarding the different configuration should be pulled into a single paragraph that describes this approach and details the pros and cons.

2024-08-27 18:46 UTC, jmendeza requested changes

2024-08-27 18:46 UTC, jmendeza commented on source/reference/modules/deployer/index.rst
> +The default behavior when a document cannot be indexed is that the Deployer logs the error and moves on. Process commits
Should it be "**Processed**" commits files ... ?

2024-08-28 15:28 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +Crafter Deployer indexes documents via the following configured items:
This is where to discuss this: https://docs.craftercms.org/en/4.1/by-role/developer/common/search.html#content-search

2024-08-28 15:29 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +
The above is done for authoring. I don't think it's done for delivery. Check that, and if it's only delivery, remove it from this.

2024-08-28 15:31 UTC, sumerjabri commented on source/reference/modules/deployer/index.rst
> +Note that indexing of documents in authoring and indexing of documents in delivery each have their own configuration.
Let's drop references to authoring; so far, no one other than internal developers cares about this. We may reference this in authoring plugin development. @alhambrav create a ticket for documenting search mechanics for plugin development to be addressed in the future.

2024-10-24 18:21 UTC, sumerjabri approved these changes

2024-10-24 18:22 UTC, merged