Add image of a page and content type model side by side in xb article #7193
craftercms/docs pull request #1876
Opened 2024-09-18 14:54 UTC by alhambrav

### Ticket reference or full description of what's in the PR
Add image of a page and content type model side by side in xb article https://github.com/craftercms/craftercms/issues/7193

2024-09-19 11:21 UTC, rart requested changes
Please see detailed notes shared over slack.

2024-09-26 21:25 UTC, sumerjabri commented
@rart bump

2024-10-04 09:04 UTC, rart approved these changes

2024-10-04 12:52 UTC, sumerjabri approved these changes

2024-10-04 12:52 UTC, merged