Add description for Deployer poolSize #7384
craftercms/docs pull request #1885
Opened 2024-10-15 12:44 UTC by alhambrav

### Ticket reference or full description of what's in the PR
Add description for Deployer poolSize https://github.com/craftercms/craftercms/issues/7384

2024-10-15 14:23 UTC, avasquez614 requested changes

2024-10-15 14:23 UTC, avasquez614 commented on source/reference/modules/deployer/index.rst
> +          poolSize: 20
I think it's also important to know that there's this pool too. The task scheduler pool is used for starting deployments on a schedule of every 10 secs, but the deployment pool is used to run all deployments

```
deployer:
  main:
    deployments:
      pool:
        # Thread pool core size
        size: 25
        # Thread pool max size
        max: 100
        # Thread pool queue size
        queue: 100
```

2024-10-22 05:28 UTC, jmendeza approved these changes

2024-11-06 19:19 UTC, avasquez614 approved these changes

2024-11-06 20:46 UTC, sumerjabri commented
@alhambrav please fix conflicts

2024-11-07 14:04 UTC, merged